export type GameStatus = "Playing" | "On Hold" | "Backlog" | "Played";

export interface Game {
    id: string; // UUID from Supabase
    title: string;
    genre: string;
    platform: string;
    rating: number | null; // 1-10 rating, null if unrated
    status: GameStatus;
    purchasing_price: number | null; // In Euros
    selling_price: number | null; // In Euros
    start_date: string | null; // ISO Date String
    end_date: string | null; // ISO Date String
    hours_played: number | null;
    created_at?: string; // Auto-generated by Supabase
    updated_at?: string; // Managed by Supabase triggers
}
