export type GameStatus = "Playing" | "On Hold" | "Backlog" | "Played" | "Wishlist";
export type GameFormat = "Digital" | "Physical" | "Cloud";

export interface Game {
    id: string; // UUID from Supabase
    title: string;
    genres: string[];
    platform: string;
    rating: number | null; // 1-10 rating, null if unrated
    status: GameStatus;
    format: GameFormat;
    purchasing_price: number | null; // In Euros
    selling_price: number | null; // In Euros
    start_date: string | null; // ISO Date String
    end_date: string | null; // ISO Date String
    hours_played: number | null;
    cover_url?: string | null;
    user_id?: string; // References auth.users(id), set automatically
    created_at?: string; // Auto-generated by Supabase
    updated_at?: string; // Managed by Supabase triggers
}
